### ISSUE TITLE
Subscription got deleted by mistake

### ISSUE THREAD

**Issue by SK-QinetiQ** [splunk/azure-functions-splunk#2]
Hi,

our Teams call logging had been running without issues for a month or so, then one time the update-subscription got a 404 back from MS Graph - even though the subscription did exist - so the update-subscription function deleted it from the blob store and we stopped getting anymore logs once it expired

here's the logs from Splunk...
[teams-calls-20211010.csv](https://github.com/splunk/azure-functions-splunk/files/7650202/teams-calls-20211010.csv)

is it possible to change the logic of the update-subscription function so it only remove subscriptions from the blob store if they are passed their expiry date? this would stop what looks like a temporary blip in MS Graph leaving you without any logs

cheers,
SK

**Comment by JasonConger** [comment]
https://github.com/splunk/azure-functions-splunk/pull/3
