### ISSUE TITLE
Support Request For Microsoft Defender For Cloud Alert EventHub Integration

### ISSUE THREAD

**Issue by bmorri13** [splunk/azure-functions-splunk#4]
Hello,

I am looking to see if it would be possible to add EventHub integration to Azure Functions similar to the current Azure Function integrations suite to support Microsoft Defender for Cloud alerts that are triggered from that (these would have been similar to the previous Azure Security Center alerts, however, it has now been rebranded.)

Main doc of the Microsoft Defender for Cloud: https://docs.microsoft.com/en-us/azure/defender-for-cloud/defender-for-cloud-introduction

**Comment by JasonConger** [comment]
This can be accomplished by [configuring continuous export to an event hub](https://docs.microsoft.com/en-us/azure/defender-for-cloud/continuous-export).  Then, use the [event-hubs-hec](https://github.com/splunk/azure-functions-splunk/tree/master/event-hubs-hec) functions to get the data pushed to your Splunk HTTP Event Collector
